### ISSUE TITLE
Deprecated function pandas.DataFrame.append

### ISSUE THREAD

**Issue by FlorianK13** [sandialabs/pvOps#47]
Hi,
when running the example code in `tutorial_textmodule.ipynb` I get an error in cell [6]
The creation of the df_remapped_assets runs code in `pvops/text/utils.py` where the function DataFrame.append is used. However, this seems to be deprecated: https://pandas.pydata.org/docs/whatsnew/v1.4.0.html?highlight=append

They advise to use pandas.concat instead.

To replicate, use pandas > 2.0

**Comment by kbonney** [comment]
Hi @FlorianK13. Thanks for taking a close look at our repo. The issue you found is something present in the last official release of the package available on pypi, but has been fixed on the latest version of `master`. We are working on doing a fresh release of our latest code, but in the meantime please use the code from git in your review. You can find installation instructions in our documentation [here](https://pvops.readthedocs.io/en/latest/pages/installation.html#installation).

**Comment by FlorianK13** [comment]
In the release v0.2.0 it works.

I have not found any details at joss on a typical workflow of such a `Review Issue`. I would propose that I close Issues when I think that they are dealt with. Are you ok with that @kbonney ?

**Comment by FlorianK13** [comment]
This comment is part of a JOSS Review: https://github.com/openjournals/joss-reviews/issues/5755

**Comment by kbonney** [comment]
> In the release v0.2.0 it works.
> 
> I have not found any details at joss on a typical workflow of such a `Review Issue`. I would propose that I close Issues when I think that they are dealt with. Are you ok with that @kbonney ?

That sounds good to me, @FlorianK13
