### ISSUE TITLE
[JOSS review] Merge Documentation and Developing pvOps

### ISSUE THREAD

**Issue by AdamRJensen** [sandialabs/pvOps#62]
To simplify the left panel, it could be considered merging the _Documentation_ and _Developing pvOps_ pages.

This is merely a suggestion, which I do not feel strongly about - but perhaps worth considering.

**Comment by kbonney** [comment]
Currently when I look at the sidebar on the docs I don't see a separate documentation entry:
![image](https://github.com/sandialabs/pvOps/assets/47759761/63c46323-4169-422e-9f59-f2057842cc23)
It does show up as a subsection in the "Developing pvOps" page, though. Let me know if I am missing something here.

**Comment by AdamRJensen** [comment]
It seems I might have been just a tad to quick when creating this issue😉
