### ISSUE TITLE
[JOSS review] Remove external licenses in NOTICE folder

### ISSUE THREAD

**Issue by AdamRJensen** [sandialabs/pvOps#63]
I think it's quite unusual to include a [folder ](https://github.com/sandialabs/pvOps/tree/master/NOTICE)with the licenses of dependencies.

One of the main reasons I'm against this is that it is a certainty that these licenses will be outdated. For example, the included pvlib license is no longer correct. pvlib does not do this, and given its affiliation with Sandia I do not think this is necessary here.

Perhaps @cwhanse can comment on this from a Sandia point of view?

**Comment by kbonney** [comment]
Addressed by #80. Resolution: deleted notice folder
