### ISSUE TITLE
[JOSS review] Add dates to What's New

### ISSUE THREAD

**Issue by AdamRJensen** [sandialabs/pvOps#64]
I highly suggest adding dates in parentheses next to the release version in the What's New files.

This makes it much easier to get a sense of the development process and informs which What's New entries are important to read:

Here's an example of how pvlib does it:
![image](https://github.com/sandialabs/pvOps/assets/39184289/895dcc50-bcbc-4c0c-af7e-e5b356292e46)

**Comment by AdamRJensen** [comment]
Also, are you planning on using semantic versioning?

**Comment by kbonney** [comment]
This is a good idea. I think we are making an effort to use semver in our github tags. The "what's new" page is pretty dated, so as part of addressing this comment I'll be adding some more entries.
