### ISSUE TITLE
[JOSS review] Change CITATION file extension from .cif to .cff

### ISSUE THREAD

**Issue by AdamRJensen** [sandialabs/pvOps#68]
The [citation file](https://github.com/sandialabs/pvOps/blob/master/citation.CIF) has an incorrect extension (**.cif**).

The correct extension should be **.cff**. See this [reference](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) for further information.

Also, the package version specified inside the citation file is incorrect.

**Comment by kbonney** [comment]
Addressed by #80. Resolution: corrected extension and updated version.
