### ISSUE TITLE
[JOSS review] Address comment stating "This needs to be reworked"

### ISSUE THREAD

**Issue by AdamRJensen** [sandialabs/pvOps#69]
Are you planning on addressing this comment before publishing the JOSS paper?

https://github.com/sandialabs/pvOps/blob/fe6e6579239ab161908fc5b0d3819b720c161f3c/pvops/iv/physics_utils.py#L08-L15

**Comment by kbonney** [comment]
Update: we are checking with @MichaelHopwood to see what should be done here.

**Comment by MichaelHopwood** [comment]
@kbonney yeah, this one would require a little bit of work. Basically, the shunt/series resistance values are defined by calculating the slope of the line between the respective ends of the curve and the knee of the curve. However, in more dirty samples, the approximation of going from end of curve to knee will be more inaccurate. 
The solution is to instead detect the linear areas. This isn't too hard of a task but will require some hyperparameters.
We can tackle this ticket after the JOSS paper, and it may be a good "First Issue" for someone :)
