### ISSUE TITLE
[JOSS review] Rename of IV package

### ISSUE THREAD

**Issue by AdamRJensen** [sandialabs/pvOps#71]
I do not think the "IV package" is actually a _package_, but rather, I believe it is a _subpackage_. 

https://github.com/sandialabs/pvOps/blob/fe6e6579239ab161908fc5b0d3819b720c161f3c/docs/pages/moduleguides/iv.rst?plain=1#L1

**Comment by kbonney** [comment]
Addressed by #80. Resolution: replaced package with module where appropriate
