### ISSUE TITLE
[JOSS review] Organize examples as tiles

### ISSUE THREAD

**Issue by AdamRJensen** [sandialabs/pvOps#72]
The visualization of the examples is currently not very pleasing: https://pvops.readthedocs.io/en/latest/pages/examples.html

Instead, I suggest having a tile layout similar to what is done in [pvlib python](https://pvlib-python.readthedocs.io/en/stable/gallery/index.html) (see screenshot below).

This may require switching to the pydata sphinx theme (which I think is recommendable nonetheless)

![image](https://github.com/sandialabs/pvOps/assets/39184289/15929c85-282e-4eef-8163-f194677dd6fd)

**Comment by kbonney** [comment]
Addressed in #81. Thanks for the resources @kandersolar.
