### ISSUE TITLE
[JOSS review] Add Statement of Need

### ISSUE THREAD

**Issue by AdamRJensen** [sandialabs/pvOps#73]
For the JOSS review, it is stated that the package documentation AND software paper should have a _Statement of Need_. Currently, I do not see a statement of need in the software documentation (readthedocs); I suggest that this is added, e.g., on the [main landing page](https://pvops.readthedocs.io/en/latest/).

**Comment by kbonney** [comment]
Addressed in #81. Statement of need on homepage.
