### ISSUE TITLE
[JOSS review assistance] tutorial_timeseries

### ISSUE THREAD

**Issue by williamhobbs** [sandialabs/pvOps#78]
Feedback on https://github.com/sandialabs/pvOps/blob/master/examples/tutorial_timeseries.ipynb:

- [x] A description of the example data is needed (each of the 3 files). I think it's ok to describe irradiance, ambient temp, and wind speed as "covariates", but a PV performance engineer might have to look up the definition of covariates (I just did...). In this case, I would also refer to those values as something like "met (meteorological) measurements" or "weather data" to help users put things in context.
- [ ] Just a suggestion, but the power vs covariates charts might be more interesting if you added a 3rd dimension with color. For example, changing the color of the markers in irrad_poa_wm2 chart based on ambient temperature, or in the other two based on irradiance.
- [x] Repeating the visualization of all three power vs covariated after normalizing feels unecessary. Maybe consider dropping the charts before normalizing?
- [ ] For final results: The straight line over nighttime that is not at zero makes the charts hard to interpret. I'm not sure what the cleanest solution is... 
  <img width="512" alt="image" src="https://github.com/sandialabs/pvOps/assets/45701090/2c0a17b6-1946-4dc8-a1a6-d9f7532fef73">
- [ ] I suggest adding scatter plots of measured vs each model
- [ ] The "Mean squared error" and "Coefficient of determination" statistics are not immediately obvious to me. For example, it is very hard to know if 1037605.81 W is a relatively large or small error value. Including something like normalized mean bias error and normalized RMSE, with a short description of what they mean, might be helpful.
- [ ] I suggest adding a PVWatts-style model and/or PVUSA/ASTM regression model to the model performance comparison. And/or cite sources on how these models are used/validated elsewhere. I don't have a good sense for how good these models are and whether they are appropriate to use.

**Comment by kbonney** [comment]
Addressed in #85
- Added a description of data
- Removed redundant plots

The rest of these points are helpful, but not critical to moving forward with the JOSS publication, so closing for now.
