### ISSUE TITLE
AdaBoostClassifier algorithm parameter

### ISSUE THREAD

**Issue by agmoore4** [sandialabs/pvOps#96]
According to scikit-learn's documentation, setting `algorithm="SAMME.R"` is deprecated and will be removed in future versions. Should be changed to `"SAMME"` to prevent breaking in the future.
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

**Comment by agmoore4** [comment]
Currently, "SAMME.R" is being used in text/defaults.py.

**Comment by kbonney** [comment]
According to the docs, the `algorithm` parameter is deprecated so let's just remove it entirely. The default is "SAMME" so it won't change the behavior.
