### ISSUE TITLE
Known bug in scikit-learn's f1_score metric

### ISSUE THREAD

**Issue by agmoore4** [sandialabs/pvOps#97]
Related to #29734 (https://github.com/scikit-learn/scikit-learn/issues/29734).

Scikit-learn's documentation states that the `pos_label` parameter is ignored in multiclass problems, but it isn't actually ignored. Since it defaults to `pos_label=1`, which isn't a label found in the dataset, the scoring fails every time, giving `np.nan`.

Setting `pos_label=None` explicitly would resolve the problem and have `f1_score` work as intended.

**Comment by agmoore4** [comment]
This fix would be relevant in tutorials/text_class_example.py, which is used in the text module tutorial

**Comment by kbonney** [comment]
How does this change the results in the tutorial?
